---
version: "3.9"
services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: Jenkins
    labels:
      type: Ci-CD tools
    ports:
    - '8080:8080'
    user: root
    volumes:
    - //var/run/docker.sock:/var/run/docker.sock
    - ./config/jenkins/jenkins_home:/var/jenkins_home
    networks:
      - devops_talk_network
  
  registry:
    image: registry:2
    container_name: registry
    labels:
      type: Ci-CD tools
    ports:
    - '5000:5000'
    networks:
      - devops_talk_network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - devops_talk_network
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - devops_talk_network

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:

networks:
  devops_talk_network:
    external:
      name: devops_talk_network