FROM docker.io/python:3.11.0b1-bullseye
COPY app/. .  
RUN echo $HTTP_PROXY $HTTPS_PROXY
RUN pip3 install -r requirements.txt  --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org

