---
version: "3.9"
services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: Jenkins
    labels:
      type: Ci-CD tools
    ports:
    - '8080:8080'
    user: root
    volumes:
    - //var/run/docker.sock:/var/run/docker.sock
  
  registry:
    image: registry:2
    container_name: registry
    labels:
      type: Ci-CD tools
    ports:
    - '5000:5000'
